[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
on_i = 1

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
[[plugins.build]]
mac = 'npm install -g tern'
unix = 'npm install -g tern'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'jade'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['ts', 'typescript']

[[plugins]]
repo = 'mhartington/deoplete-typescript'
depends = ['deoplete.nvim', 'tsuquyomi']
on_ft = ['ts', 'typescript']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown', 'mkd']

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['webapi-vim']
on_ft = ['md', 'markdown', 'mkd']

[[plugins]]
repo = 'mattn/webapi-vim'
on_ft = ['md', 'markdown', 'mkd']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
