[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_mac.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
  '''

# [[plugins]]
# repo = 'neomake/neomake'
# hook_add = '''
# let g:neomake_javascript_enabled_makers = ['standard']
# let g:neomake_open_list = 2
# let g:neomake_verbose = 2
# autocmd! BufWritePost * Neomake
# '''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
